### ISSUE TITLE
If gEDA supports multiple net-names for a net (aliases?), could we get some more verbose net-names?

### ISSUE THREAD

**Issue by nmz787** [kanzure/culture_shock#1]
For example, PA4 appears to be coming off a voltage divider and heading to the STM32's ADC1 input (which is muxed on PA4, according to the controller's datasheet). If gEDA can support multiple net-names on a net, then it would be nice to add another name to the PA4 net... HV_SENSE or something.

**Comment by jgriessen** [comment]
Sure thing Nathan.  I'll make them like PA4_HV_SENSE.  HV_SENSE is just right as a name for this.  Thanks for reviewing.

**Comment by nmz787** [comment]
Issue was solved [in this commit](https://github.com/kanzure/culture_shock/blob/04f44e49732baf2d4784e47160a141f80ddaa6bb/kvboard.sch)
and schematic PNG updated [in this commit](https://github.com/kanzure/culture_shock/commit/39a35a4c5a8d66eba69640c86b20827881aa05fd)
